name: SkyblockIsland
version: '${project.version}'
main: me.wizzo.skyblockisland.SkyblockIsland
api-version: '1.20'
author: wiz
commands:
  island:
    description: island command
    aliases:
      - is
